export const cex = [
    "Binance CEX",
    "OKX",
    "Bitfinex",
    "Bybit",
    "Crypto-com",
    "Huobi",
    "Kucoin",
    "Deribit",
    "Gate-io",
    "Bitget",
    "MEXC",
    "Bitmex",
    "SwissBorg",
    "MaskEX",
    "Korbit",
    "Nexo",
    "Okcoin",
    "Phemex",
    "Firi",
    "Cake DeFi",
    "WOO X",
    "CoinDCX",
    "Coinsquare",
    "Hotbit",
    "NBX",
    "Latoken",
    "BitMake",
    "BitVenus",
    "Kraken",
    "Gemini",
    "Crypto.com",
    "Coinbase"
  ];
  